export const fonts = [
  { name: "Alfa Slab One" },
  { name: "Amatic SC" },
  { name: "Anton" },
  { name: "Architects Daughter" },
  { name: "Arial" },
  { name: "Arsenal" },
  { name: "Audiowide" },
  { name: "Baskervville" },
  { name: "Betas Neue" },
  { name: "Cabin" },
  { name: "Cambria" },
  { name: "Chalkboard" },
  { name: "Courier New" },
  { name: "DM Sans" },
  { name: "DM Serif Display" },
  { name: "Do Hyeon" },
  { name: "Exo 2" },
  { name: "Fahkwang" },
  { name: "Fira Sans" },
  { name: "Fjalla One" },
  { name: "Gemunu Libre" },
  { name: "Georgia" },
  { name: "Gluten" },
  { name: "Hanson" },
  { name: "Helvetica" },
  { name: "Inconsolata" },
  { name: "Inter" },
  { name: "Josefin Sans" },
  { name: "Kanit" },
  { name: "Kanone Kaffeesatz" },
  { name: "Karla" },
  { name: "Knewave" },
  { name: "Krona One" },
  { name: "Lato" },
  { name: "Libre Franklin" },
  { name: "Lobster" },
  { name: "Luckiest Guy" },
  { name: "Manrope" },
  { name: "Maven Pro" },
  { name: "Menlo" },
  { name: "Merriweather" },
  { name: "Monaco" },
  { name: "Montserrat" },
  { name: "Noto Sans Display" },
  { name: "Noto Sans Mono" },
  { name: "Noto Serif Display" },
  { name: "Nunito Sans" },
  { name: "Outfit" },
  { name: "Open Sans" },
  { name: "Oswald" },
  { name: "PT Sans" },
  { name: "Permanent Marker" },
  { name: "Play" },
  { name: "Playfair Display" },
  { name: "Poppins" },
  { name: "Press Start 2P" },
  { name: "Prompt" },
  { name: "Raleway" },
  { name: "Ranchers" },
  { name: "Righteous" },
  { name: "Roboto" },
  { name: "Roboto Mono" },
  { name: "Rubik" },
  { name: "SFMono-Regular" },
  { name: "Satisfy" },
  { name: "Shadow Into Light" },
  { name: "Source Code Pro" },
  { name: "Source Serif Pro" },
  { name: "Space Grotesk" },
  { name: "Space Mono" },
  { name: "Staatliches" },
  { name: "Syne" },
  { name: "System-ui" },
  { name: "Times New Roman" },
  { name: "Titillium Web" },
  { name: "Ubuntu" },
  { name: "VT323" },
  { name: "Vidaloka" },
  { name: "Work Sans" },
  { name: "comic sans ms" },
  { name: "monospace" },
  { name: "uisecondaryerif" },
  { name: "Zilla Slab" },
];