name: Automate PR into Prod
on:
  schedule:
    # Runs every day at 5:30pm PST and 12:00pm PST each day except for Sunday*
    - cron: '30 1,20 * * 1-6'
  workflow_dispatch:

jobs:
  pull-request:
    name: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: repo-sync/pull-request@v2
        name: pull-request
        with:
          source_branch: 'master'
          destination_branch: 'prod'
          pr_title: 'Deployment into prod'
          pr_body: '👑 *An automated PR*'
          pr_reviewer: 'jennifertrin'
          pr_assignee: 'jadbox'
          pr_draft: false
          pr_allow_empty: false
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
